version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: postdb.Dockerfile
    ports:
      - 5984:5984
    environment:
      - PGHOST=db
      - PGPASSWORD=admin
      - PGUSER=admin
      - PGPORT=5432
    depends_on:
      - db
  replicator:
    build: 
      context: .
      dockerfile: replicator.Dockerfile
    environment:
      - PGHOST=db
      - PGPASSWORD=admin
      - PGUSER=admin
      - PGPORT=5432
    depends_on:
      - db   
      - web   
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports:
      - 5432:5432